#!/usr/bin/env sh

JAR=target/lama-graalvm-1.0-SNAPSHOT.jar

# DEBUG='-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005'

# TODO fix stack overflow

"$JAVA_HOME/bin/java" -Xss2m $DEBUG "-Dtruffle.class.path.append=$JAR" -jar "$JAR" "$@"
